name: Build and Test VM

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: actions/setup-python@v4
      if: startsWith(matrix.container,'ubuntu')
      with:
        python-version: '3.8'
    - name: build
      run: 
           |
          sudo apt install llvm-15-dev
          cmake -B build -DCMAKE_BUILD_TYPE=Debug
          cmake --build build --target all -j
    - name: run testsuit x86
      shell: bash
      run: |
        python3.8 -m venv vm/test
        source vm/test/bin/activate
        pip install -r vm/test/requirements.txt
        # make build # or build-arm32 build-arm64
        make -C vm test-vm -j